name: Test and deploy to Firebase Functions on merge
'on':
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/firebase-functions-*.yml'
jobs:
  build_and_deploy:
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache functions/node_modules
        uses: actions/cache@v2
        id: cache-functions-node_modules
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('functions/yarn.lock') }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Cache firebase emulators
        uses: actions/cache@v2
        id: cache-firebase-emulators
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn install --frozen-lockfile && yarn --cwd functions install --frozen-lockfile
      - run: yarn test:ci
      - run: yarn deploy --only functions --token "${{ secrets.FIREBASE_TOKEN_AMBERBROOCH }}"
