name: Test and deploy to Firebase Hosting on PR
'on':
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'functions/**'
      - '.github/workflows/firebase-functions-*.yml'
env:
  flutter_version: "2.5.3"
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Cache functions/node_modules
        uses: actions/cache@v2
        id: cache-functions-node_modules
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('functions/yarn.lock') }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Cache firebase emulators
        uses: actions/cache@v2
        id: cache-firebase-emulators
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn install --frozen-lockfile && yarn --cwd functions install --frozen-lockfile
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - run: rm web/index.html && mv web/index_prod.html web/index.html
      - run: flutter pub get
      - run: yarn test:ci
      - run: grep "^version:" pubspec.yaml | sed 's/^version:\s*\(.*\)\s*$/const version="\1";/g' > lib/config/version.dart
      - run: flutter build web --web-renderer html --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMBERBROOCH }}'
          projectId: amberbrooch
      - run: curl https://asia-northeast1-amberbrooch.cloudfunctions.net/api/setup
